### ISSUE TITLE
Error: error in building shared-object library from C snippets: in ‘Cbuilder’

### ISSUE THREAD

**Issue by braunheim** [kingaa/pomp#104] opened 2020-04-08 12:53 UTC
Restarting R session...

> install.packages("pomp",repos="https://kingaa.github.io/")
Installing package into ‘\\c4usc1syn06g003/PHSSHARE/USERS/bbraunhei/My Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://kingaa.github.io/bin/windows/contrib/3.6/pomp_2.7.2.1.zip'
Content type 'application/zip' length 1511381 bytes (1.4 MB)
downloaded 1.4 MB

package ‘pomp’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\bbraunhei\AppData\Local\Temp\RtmpgBfJm6\downloaded_packages

> cat("#include <R.h>
+ void hello (void) {
+ Rprintf(\"hello world!\\n\");
+ }",file="hello.c")
> system("R CMD SHLIB hello.c")
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c hello.c -o hello.o
C:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o hello.dll tmp.def hello.o -LC:/PROGRA~1/R/R-36~1.1/bin/x64 -lR
[1] 0
> dyn.load(paste0("hello",.Platform$dynlib.ext))
> .C("hello",PACKAGE="hello")
hello world!
list()

> library(pomp)
Welcome to pomp!
As of version 2.7.1.0, important changes have been made to the
default settings of the particle filtering algorithms in
‘pfilter’, ‘mif2’, ‘pmcmc’, ‘bsmc2’.
These changes are not backward compatible.
See the package NEWS for the details.

For information on upgrading your pomp version < 2 code, see the
“pomp version 2 upgrade guide” at https://kingaa.github.io/pomp/.

Warning message:
package ‘pomp’ was built under R version 3.6.3 

> 
> niamey <- read.csv("http://kingaa.github.io/clim-dis/parest/niamey.csv")
> 
> pomp(
+   data=subset(niamey,community=="A",select=-community),
+   times="biweek",t0=0,
+   skeleton=vectorfield(
+     Csnippet("
+          DS = -Beta*S*I/N;
+          DI = Beta*S*I/N-gamma*I;
+          DR = gamma*I;")
+   ),
+   rinit=Csnippet("
+          S = S_0;
+          I = I_0;
+          R = N-S_0-I_0;"),
+   statenames=c("S","I","R"),
+   paramnames=c("Beta","gamma","N","S_0","I_0")
+ ) -> niameyA
Error: error in building shared-object library from C snippets: in ‘Cbuilder’: compilation error: cannot compile shared-object library ‘C:/Users/BBRAUN~1/AppData/Local/Temp/RtmpgBfJm6/7820/pomp_60bd1e4a1290378015ad21533b249ea5.dll’: status = 1
compiler messages:
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c C:/Users/BBRAUN~1/AppData/Local/Temp/RtmpgBfJm6/7820/pomp_60bd1e4a1290378015ad21533b249ea5.c -o C:/Users/BBRAUN~1/AppData/Local/Temp/RtmpgBfJm6/7820/pomp_60bd1e4a1290378015ad21533b249ea5.o
C:/Users/BBRAUN~1/AppData/Local/Temp/RtmpgBfJm6/7820/pomp_60bd1e4a1290378015ad21533b249ea5.c:5:104: fatal error: \c4usc1syn06g003/PHSSHARE/USERS/bbraunhei/My Documents/R/win-library/3.6/pomp/include/pomp.h: No such file or directory
 #include <\c4usc1syn06g003/PHSSHARE/USERS/bbraunhei/My Documents/R/win-library/3.6/pomp/include/pomp.h>
                                                                                        
In addition: Warning message:
In system2(command = R.home("bin/R"), args = c("CMD", "SHLIB", "-c",  :
  running command '"C:/PROGRA~1/R/R-36~1.1/bin/R" PKG_CPPFLAGS="-I\\c4usc1syn06g003/PHSSHARE/USERS/bbraunhei/My Documents/R/win-library/3.6/pomp/include -IC:/Users/bbraunhei/COVID-19 (R)/COVID_interventions-master" CMD SHLIB -c -o C:/Users/BBRAUN~1/AppData/Local/Temp/RtmpgBfJm6/7820/pomp_60bd1e4a1290378015ad21533b249ea5.dll C:/Users/BBRAUN~1/AppData/Local/Temp/RtmpgBfJm6/7820/pomp_60bd1e4a1290378015ad21533b249ea5.c' had status 1

**Comment by kingaa** [comment] 2020-04-08 21:18
This is a duplicate of #103.

**Closed as completed by kingaa** 2020-04-08 21:18 UTC
Labels: duplicate
