### ISSUE TITLE
Recommended optimization for traj.match

### ISSUE THREAD

**Issue by mikeaalv** [kingaa/pomp#58] opened 2017-11-30 15:26 UTC
For the function of `traj.match` to solve ODE with reporting error, what is the recommended way for optimization?

I have try Nelder-Mead, subplex and SANN. It is highly likely that subplex give me some error/complaining about initial value. I have try use Nelder-Mead or SANN--> Nelder-Mead. However, increasing sample size in parameter space will give me better result in log likelihood. This probably mean that I didn't arrive the global optimum.

I have 10-20 parameters.

What would the recommended way to solve the optimization problem?

**Comment by kingaa** [comment] 2017-12-15 13:14
This is a very good question.  It is good because it has no simple answer.  The "no free lunch" theorem tells us that, for any optimization algorithm, there is an objective function such that that optimization algorithm performs worse than a brute-force grid search.  In the specific context of POMP models, likelihood surfaces are frequently inconveniently complex, with narrow, nonlinear ridges, curvature that varies across the parameter space, multiple peaks, and so on.  In the more specific context of deterministic POMP models, i.e., those for which maximum likelihood is trajectory matching, the situation can be even worse in that the likelihood surface can be extremely rugged, even fractal.

In the face of this complexity, what is one to do?  First, one recognizes that the problem is a global optimization problem.  In fact, it is more than that: one should seek not only the global maximum of the likelihood, but the location of globally suboptimal but local maxima, if they exist, as well as the structure of the likelihood surface in the neighborhood of each maximum.  This is a hard problem.

It seems evident that you have already recognized this, or most of it.  Yes, there is a role for so-called "global optimization" algorithms, but you must realize that there are no practical guarantees that any given algorithm will solve the problem.  Thus, for example, although simulated annealing (SANN) is guaranteed to ultimately find the global maximum, the timescale of that guarantee is frequently so long as to be meaningless for all practical purposes.

In my own work, I tend to rely on multi-start local searches.  Indeed, in a global optimization problem, one cannot avoid needing to use multiple starts to be confident one has found the global optimum.  I see that you have already discovered **nloptr**'s `NLOPT_GN_MLSL` option, which is a convenient way of implementing such a search.

I'm going to close this issue now, but feel free to reopen it if you want to discuss further.

**Comment by mikeaalv** [comment] 2017-12-15 20:45
Thanks a lot for your wonderful education.

I didn't realize that `traj.match` can generally have worse situation than stochastic modeling. It seems to me that stochastic model are generally more "complex". What's generally happening there?

What I understand of your second graph and the optimization is that we want to find the "range" of global optimum and the surface nearby. Is that what you are saying?

**Closed as completed** 2018-01-06 17:48 UTC
Labels: help wanted
