### ISSUE TITLE
Using partrans and parameter_trans

### ISSUE THREAD

**Issue by gmferra** [kingaa/pomp#92] opened 2019-06-12 19:37 UTC
I'm trying to update my code for version 2 of pomp, and I'm having trouble incorporating constraints on my parameters. 

<img width="263" alt="Screen Shot 2019-06-12 at 3 28 37 PM" src="https://user-images.githubusercontent.com/51380053/59380423-14941200-8d27-11e9-9394-c9b2632861ef.png">
<img width="419" alt="Screen Shot 2019-06-12 at 3 28 53 PM" src="https://user-images.githubusercontent.com/51380053/59380427-18279900-8d27-11e9-80c0-8ed59bf5e773.png">
<img width="481" alt="Screen Shot 2019-06-12 at 3 29 09 PM" src="https://user-images.githubusercontent.com/51380053/59380428-18279900-8d27-11e9-80fa-9919b417a3ec.png">

Right now I've called partrans in mif2, however I keep getting the error below:

<img width="521" alt="Screen Shot 2019-06-12 at 3 31 41 PM" src="https://user-images.githubusercontent.com/51380053/59380475-35f4fe00-8d27-11e9-8f80-52234f4c2abc.png">

Then, when I call partrans in pomp:

<img width="436" alt="Screen Shot 2019-06-12 at 3 34 29 PM" src="https://user-images.githubusercontent.com/51380053/59380654-96843b00-8d27-11e9-96e1-1efaa05be0f5.png">

I get this error:

<img width="722" alt="Screen Shot 2019-06-12 at 3 34 55 PM" src="https://user-images.githubusercontent.com/51380053/59380685-a56aed80-8d27-11e9-8b36-3ebb0a81a873.png">

I'm not sure where to go to from here. 

Thank you in advance.

**Comment by kingaa** [comment] 2019-06-13 18:51
You don't mention it explicitly, but I gather from the first error message that you're performing the call to mif2 inside a `foreach` loop.  If the `foreach` backend is running independent slave **R** sessions, then there is the possibility that `foreach` has not worked out that it needs to export `fromEst` and `toEst` to the slave sessions.  You can force it to do so by naming those objects in the `.export` argument.  See `?foreach` for more on that.

Now, on to the second error message.  As it states, this is a failure to compile the C library, presumably because the C code is invalid.  If you post a reproducible example, I would probably be able to be more specific.

By the way, you can make things a bit simpler for yourself by using the `log` and `logit` arguments to `parameter_trans`.  For example, replacing your codes above by
```
...
partrans=parameter_trans(log=c("psi","R0"),logit=c("q","gamma","rho")),
paramnames=c("psi","R0","rho","gamma","q"),
...
```
will achieve the same effect.

**Comment by kingaa** [comment] 2019-06-21 15:41
@gmferra: on the assumption that this has resolved your difficulties, I am going to close this issue now.  Feel free to reopen it if has not in fact been resolved, or if you want to continue the discussion.

**Closed as completed by kingaa** 2019-06-21 15:41 UTC
Labels: help wanted

**Comment by gmferra** [comment] 2019-06-21 15:52
Hi,

Yes, I was able to resolve this issue. I apologize for not responding sooner. Thank you for your help!

Best,
Gabby
