### ISSUE TITLE
running pomp on linux server

### ISSUE THREAD

**Issue by mikeaalv** [kingaa/pomp#59] opened 2017-12-08 00:18 UTC
I am running pomp on a linux server.
I find that after running pomp in one node, there would be difficulty in running the second one. The second one would be just taking long time in the pomp function without and error presented. If I stop that running. I will get error like: 
```
make: *** Deleting file `/tmp/RtmpBuPsU4/494424/pomp_a9f0ff2e4dc4a410222dd99cb95eb4fe.so'
make: *** [/tmp/RtmpBuPsU4/494424/pomp_a9f0ff2e4dc4a410222dd99cb95eb4fe.so] Interrupt
Error: in 'pomp': error in building shared-object library from C snippets: in 'pompCBuilder': compilation error: cannot compile shared-object library '/tmp/RtmpBuPsU4/494424/pomp_a9f0ff2e4dc4a410222dd99cb95eb4fe.so': status = 1
Execution halted
```
I am not quite sure what happened here. Any possible way to run it on the same server on several nodes?

**Comment by kingaa** [comment] 2017-12-08 12:54
@mikeaalv, I'm not sure what you mean by "linux server".  From your allusion to multiple nodes, I surmise you may be working on a linux cluster.  Many folks run pomp on linux machines and on linux clusters all the time.  There can always be issues in the configuration of the computing environment (though these are usually minimal to non-existent under common linux configurations), and, when they occur on clusters, they are always more complicated.  

The error you quote is simply **pomp** telling you it can't compile the shared-object library.  There are lots of reasons why this might be the case.  The fact that you can compile it sometimes, but not others, implies that the problem is not with the code *per se* but somewhere else.  The fact that many people successfully accomplish this on a wide range of hardware and in a variety of environments suggests that "somewhere else" is probably outside of **pomp**.  That leaves the computing environment, which is a pretty broad category that includes compilers and libraries, file-system, versions of **R** and its packages, network connectivity, etc.  I recommend discussing with someone who is familiar with (and able to modify or repair) the machines you are working on.

**A workaround:**  
Use the `cdir,` and `cfile` options in your current call to `pomp` to put the C code file in a fixed location, i.e., not in the temporary directory.  You might put it in the current working directory, for example.  You can recompile the shared-object library by hand (`R CMD SHLIB ...`) and diagnose any problems that occur there.  Afterward, you'll have to rewrite your call to the `pomp` constructor to replace the Csnippets with references the functions in your library.  Note that you'll have to manually load and unload the library in any **R** session that uses it (`dyn.load()`, ...).  This workaround completely avoids the compilation step that is triggered when `pomp` is called with Csnippets.  There may still be problems, e.g., if the nodes can't all see the shared-object library, but compilation won't be one of them.

**Comment by mikeaalv** [comment] 2017-12-08 17:19
Thanks a lot. I will try with your suggestions.

**Comment by kingaa** [comment] 2017-12-15 13:15
I am closing this issue.  Feel free to reopen if more discussion is warranted.

**Closed as completed by kingaa** 2017-12-15 13:15 UTC
Labels: help wanted
